name: Autobots Go!
on:
  workflow_dispatch:
  push:
    tags: 'deploy-*'

jobs:
  deploy-autobot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22.4'

      - name: Build Autobot
        run: go build -o autobot ./auto/main.go
