name: Deploy Blog
on:
  workflow_dispatch:
  push:
    tags:
      - 'publish-*'

jobs:
  deploy-blog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install required software
        run: |
          sudo apt-get update
          sudo apt-get install -y hugo awscli npm

      - name: Install
        run: |
          npm install
          hugo

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.S3_BUCKET_REGION }}

      - name: Sync to S3
        run: aws s3 sync public/ s3://${{ secrets.S3_BUCKET }} --delete

      - name: Create CloudFront invalidation
        run: |
          invalidationBatch=$(jq -n --arg callerReference $(date -u +"%Y-%m-%dT%H:%M:%SZ") --argjson items '["/*"]' '{"Paths": {"Quantity": 1, "Items": $items}, "CallerReference": $callerReference}')
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --invalidation-batch "$invalidationBatch"
