name: Deploy Blog
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
jobs:
  deploy-blog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check Blog Changes
        id: check_blog_changes
        run: |
          if git diff --name-only HEAD^ HEAD | grep 'blog/'; then
          echo "Blog has changed"
          echo "::set-output name=blog_changed::true"
          else
              echo "Blog has not changed"
              echo "::set-output name=blog_changed::false"
          fi
